### ISSUE TITLE
Must supply cloud_name error message

### ISSUE THREAD

**Issue by oseifrimpong** [FeiyChina/feiy#363]
Hello there, 

I am having an issue signing up in development mode. I get the error below when I click on the signup button. 

`Must supply cloud_name`

I know it is associated with cloudinary. 
Can anyone help? 
Thanks.

**Comment by agallet** [comment]
Sry guy, no idea...

**Comment by oseifrimpong** [comment]
Okay, thanks!

**Comment by Sebachowa** [comment]
What information do you have in the application.yml?? You should have the cloudinary api key there. Usually that issue is when you didnt setup properly your cliudinary api keys..

**Comment by Sebachowa** [comment]
Please check figaro docs https://github.com/laserlemon/figaro/blob/master/README.md

**Comment by Sebachowa** [comment]
The owner of the cloudinary account should give you the api keys. Because application.yml is ignored by git.

**Comment by xnagpa** [comment]
Hello @oseifrimpong! 
The deal is, you need to go and register your own cloudinary account. 
Then dowload yml file with config from cloudinary site. 
Then put obtained cloudinary.yml file to your config folder. 
Error must disappear.

**Comment by xnagpa** [comment]
@oseifrimpong  Do you still experience the issue? Shouldn't we close the issue if everything is ok?

**Comment by oseifrimpong** [comment]
Yes I got it! We can close this issue now.
