### ISSUE TITLE
Organisation website 

### ISSUE THREAD

**Issue by Pauline0504** [FeiyChina/feiy#378]
Currently an organisation doesn't have their website appearing when we go consult their organisation page. 

But they are actually entering their website when creating their organisation -> we can see the website only on the backoffice 

![capture d ecran 2018-02-05 a 17 34 59](https://user-images.githubusercontent.com/28041040/35797533-fae64482-0a9a-11e8-9615-12abd069e077.png)

Can we make it appear on their organisation page also?

**Comment by xnagpa** [comment]
Done
<img width="1216" alt="2018-02-16 5 53 59" src="https://user-images.githubusercontent.com/4035895/36291753-f057f42a-12dd-11e8-9c5e-7b14cf06d922.png">
