### ISSUE TITLE
Edit profile/ edit account- error page

### ISSUE THREAD

**Issue by Pauline0504** [FeiyChina/feiy#407]
I noticed that when we click on those 2 button "edit profile" and "edit account" it leads to an error page. 
I am wondering if it's possible that this kind of bugs just appears by itself? Was working and break for some reasons on its own? And if yes how come? Because the original code had some mistakes or something like this..? - Because I feel it was working at the very beginning (but maybe it was not)

![capture d ecran 2018-02-27 a 18 16 00](https://user-images.githubusercontent.com/28041040/36723314-dd8b36fc-1bea-11e8-9a79-fcaa16a03525.png)
![capture d ecran 2018-02-27 a 18 16 05](https://user-images.githubusercontent.com/28041040/36723317-ddc14044-1bea-11e8-944a-4e5749bb45e2.png)
![capture d ecran 2018-02-27 a 18 16 33](https://user-images.githubusercontent.com/28041040/36723319-ddf6e960-1bea-11e8-9315-92139e5e79bd.png)

**Comment by xnagpa** [comment]
It really worked correctly. I'll watch this.

**Comment by xnagpa** [comment]
And the answer is: "Write tests". Thus you can be sure, that some functionality works fine

**Comment by xnagpa** [comment]
@Pauline0504  It should be vanished now

**Comment by Pauline0504** [comment]
Oh ok thanks!
